controller_manager:
  update_rate: 100
  use_sim_time: true

position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - joint_z
    - HFE
    - KFE
  joint_z:
    pid: {p: 10000.0, i: 100000.0, d: 100.0}
  HFE:
    pid: {p: 100.0, i: 0.0, d: 10.0}
  KFE:
    pid: {p: 100.0, i: 0.0, d: 10.0}
  
joint_state_controller:
  type: joint_state_controller/JointStateController
  joints:
    - joint_z
    - HFE
    - KFE
  publish_rate: 100