robot:
    interface: enp0s31f6
    joint_modules:
        motor_numbers: [0, 1]
        motor_constants: 0.025
        gear_ratios: 1.
        max_currents: 20.
        reverse_polarities: [
            false, false
        ]
        lower_joint_limits: [
            -3.4, -3.4
        ]
        upper_joint_limits: [
            +3.4, +3.4
        ]
        max_joint_velocities: 200.
        safety_damping: 0.0
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      AUTO, AUTO
    ]
    position_offsets: [
        2.18667, -0.889898
    ]
    calib_order: [1, 1]
    calib_pos: [0.78, 0.78]
    Kp: 10.0
    Kd: 0.0025
    T: 2.5
    dt: 0.001
